### ISSUE TITLE
There is too many ways of running a microros agent.

### ISSUE THREAD

**Issue by Shamiivan** [Sim2Capstone/twip#1]

**Comment by AugustDG** [comment]
What would be the preferred way in your opinion?

**Comment by Shamiivan** [comment]
Docker as of now. I should have clarified, many is not a bad thing as long as it's organized. I opened the issue as todo in the future, because I was working on something else. I Eventually I want to have build and run scripts that are versatile.

**Comment by AugustDG** [comment]
Okay, perfect!
